{% set name = "pyrobuf" %}
{% set version = "0.9.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9cca7f992c674645522247e23cf6c4d81cca42e5a65e4ae1d05f3967b0c07a80

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - pyrobuf = pyrobuf.__main__:main

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
  host:
    - python
    - pip
    - msinttypes  # [win]
    - jinja2 >=2.8
    - cython >=0.23
    - pytest-runner
  run:
    - jinja2 >=2.8
    - cython >=0.23
    - python

test:
  imports:
    - pyrobuf
  commands:
    - pyrobuf --help

about:
  home: https://github.com/appnexus/pyrobuf
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Pyrobuf is an alternative to Google's Python Protobuf library.
  description: |
    Pyrobuf is an alternative to Google's Python Protobuf library.

    It generates lightning-fast Cython code that's 2-4x faster than Google's
    Python Protobuf library using their C++ backend and 20-40x faster than
    Google's pure-python implementation.

    What's more, Pyrobuf is self-contained and easy to install.

  dev_url: https://github.com/appnexus/pyrobuf

extra:
  recipe-maintainers:
    - hmaarrfk
