appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: YiAWuI+6UKYCm0SZOlVSU0jvKNbgsNlMEMxFDbYPVt4gNEGBIiek+pOOYyOFx1v9MInkg7CMMBzloCXYua6iSPrEKYxFQTjE03OaYGoSI8WqwuD70LcKJ82Iu+EvDb8ef1AInyohIKTPU9dg7r9g1dGcz4fW20RTs//Dvb05A3CAX8ZxyV+Wya/Z9llZYbn+mt+pgeKvoCECCf8DV4TaR3sUt/ZsC+exidu9Nwa7GWUFCFw+36QoXHQeTrBjemLfP2R8qVhXxcBOkEkc9Uv3DnzYCnSy03UxwAAGhjENtqst+2lJAtQSfG0csYa9ssIy4hEWn4mjBTx7yU2fxJMW7H/IbtbNuKm2c16GdnCRsTckks5rAiWuiApcV4BuJl6M8p2hxs9/RkBvt4ML+GUG6H/juTQjv47O7ye1o+/UzRQoIlAT2nkNq2/pWPXFCf1n8pDujV8/MjMKRyhPZ5zMwVjeRFFSbHoWs1fzz8kFgf6V4mQ+KskF+l+wtRrMYewzEfKekeYZJMrHFFAbSDans8v/fJss/ziEnXJ8cQBtSLrrptV6OMoBfixFk63Z6UBShjEXw1SyhgLH8lvft3Nu/i+GjXSo4MvUQioff/qHKPhn1eWrYZiXzIjpwquCZ90Q0rd1Clx4bOaZAmtNuwx1iOPJMr0Jfax70SI/Jgt3okc=}
provider:
  win: azure
conda_forge_output_validation: true
